### ISSUE TITLE
cannot import name ctypes_interface

### ISSUE THREAD

**Issue by chancsc** [bluemellophone/detecttools#1]
I installed the detectools with the following command but when trying to import I encountered the below issues, need help. Thanks

> > python setup.py build
> > sudo python setup.py install

---

  File "/usr/local/lib/python2.7/dist-packages/detecttools-1.0.0.dev1-py2.7.egg/detecttools/**init**.py", line 4, in <module>
    from . import ctypes_interface
ImportError: cannot import name ctypes_interface

> > > import detecttools
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/detecttools-1.0.0.dev1-py2.7.egg/detecttools/**init**.py", line 6, in <module>
> > >     from . import pascaldata
> > > ImportError: cannot import name pascaldata

**Comment by chancsc** [comment]
I think I found the reason, the setup.py doesn't include the "pascaldata", updated the setup.py and rerun the build & install, it's ok now. Let me know if it's not correct.

....
    packages=['detecttools',
              'detecttools.ctypes_interface',
              'detecttools.directory',
              'detecttools.ibeisdata',
              'detecttools.pascaldata',
              'detecttools.pypascalmarkup',
              ],
....

**Comment by bluemellophone** [comment]
Fixed.
